version: '3.8'

services:
  catalog_api:
    build:
      context: ./catalog_api
      dockerfile: Dockerfile
    container_name: catalog_api
    ports:
      - "5040:5040"
    networks:
      - api_network
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5040

  poke_api:
    build:
      context: ./poke_api
      dockerfile: Dockerfile
    container_name: poke_api
    ports:
      - "5041:5041"
    networks:
      - api_network
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5041

  gateway_api:
    build:
      context: ./gateway_api
      dockerfile: Dockerfile
    container_name: gateway_api
    ports:
      - "5042:5042"
    networks:
      - api_network
    depends_on:
      - catalog_api
      - poke_api
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5042

networks:
  api_network:
    driver: bridge
